/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as KullanimSartlariRouteImport } from './routes/kullanim-sartlari'
import { Route as CvEncodedRouteImport } from './routes/cv.$encoded'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimSartlariRoute = KullanimSartlariRouteImport.update({
  id: '/kullanim-sartlari',
  path: '/kullanim-sartlari',
  getParentRoute: () => rootRouteImport,
} as any)
const CvEncodedRoute = CvEncodedRouteImport.update({
  id: '/cv/$encoded',
  path: '/cv/$encoded',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/cv/$encoded': typeof CvEncodedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/cv/$encoded': typeof CvEncodedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/cv/$encoded': typeof CvEncodedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gizlilik' | '/kullanim-sartlari' | '/cv/$encoded'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gizlilik' | '/kullanim-sartlari' | '/cv/$encoded'
  id: '__root__' | '/' | '/gizlilik' | '/kullanim-sartlari' | '/cv/$encoded'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GizlilikRoute: typeof GizlilikRoute
  KullanimSartlariRoute: typeof KullanimSartlariRoute
  CvEncodedRoute: typeof CvEncodedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-sartlari': {
      id: '/kullanim-sartlari'
      path: '/kullanim-sartlari'
      fullPath: '/kullanim-sartlari'
      preLoaderRoute: typeof KullanimSartlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$encoded': {
      id: '/cv/$encoded'
      path: '/cv/$encoded'
      fullPath: '/cv/$encoded'
      preLoaderRoute: typeof CvEncodedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GizlilikRoute: GizlilikRoute,
  KullanimSartlariRoute: KullanimSartlariRoute,
  CvEncodedRoute: CvEncodedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
